### ISSUE TITLE
Charmap error Windows 11

### ISSUE THREAD

**Issue by u-Aymane** [kensh1ro/camouflage#1]
```bash
$ python camouflage.py -p tcp -H 192.168.213.128:4444 --packer compile -o Final
Traceback (most recent call last):
  File "C:\Users\Aymane\Desktop\Windows 11 Dev Kit\camouflage\camouflage.py", line 199, in <module>
    print(banner)
  File "C:\Users\Aymane\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-14: character maps to <undefined>```

**Comment by kensh1ro** [comment]
It looks like your terminal is not able to print the banner, comment line 199 "print(banner)", it should work for you, in that case I shall edit the script to catch this error

**Comment by u-Aymane** [comment]
Thanks appreciate that!
